services:

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.s_${PROJECT_NAME}.loadbalancer.server.port=3000"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`www.${PROJECT_BASE_URL}`) || Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      # Redirect normal web to www
      - "traefik.http.routers.${PROJECT_NAME}.middlewares=${PROJECT_NAME}_www_redirect"
      - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.regex=^(https?)://${PROJECT_BASE_URL}/(.*)$$"
      - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.replacement=https://www.${PROJECT_BASE_URL}/$${2}"
      - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.permanent=true"

  backend:
    build:
      args:
      - NODE_ENV=development
      context: backend
      target: development
    command: npm run start-watch
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public

networks:
  public:
    name: other
    external: true

volumes:
  back-notused:
