version: "3.9"

services:

    nginx:
        image: wodby/nginx:latest
        container_name: "${PROJECT_NAME}_nginx"
        restart: always
        environment:
            NGINX_SERVER_ROOT: /var/www/html/www
        volumes:
            - ./src/:/var/www/html
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`www.${PROJECT_BASE_URL}`) || Host(`${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web,websecure"
            - "traefik.http.routers.${PROJECT_NAME}.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=myresolver"
            - "traefik.http.routers.${PROJECT_NAME}.middlewares=${PROJECT_NAME}_https_redirect"
            # Redirect https, www
            - "traefik.http.routers.${PROJECT_NAME}.middlewares=${PROJECT_NAME}_www_redirect"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.scheme=https"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.permanent=true"
            - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.regex=^(https?)://${PROJECT_BASE_URL}/(.*)$$"
            - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.replacement=$${1}://www.${PROJECT_BASE_URL}/$${2}"
            - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.permanent=true"

networks:
    web:
        name: www_kimisek
        external: true
